version: '3.4'

services:
  webappclient:
    image: webappclient
    build:
      context: webapp-client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
